config {
  type: "table",
  bigquery: { 
    partitionBy:"DATE(ingest_time)",
    partitionExpirationDays: 30,
    clusterBy:["fruit"]
  }
}

SELECT
  "apples" AS fruit,
  2 AS count,
  CURRENT_TIMESTAMP() as ingest_time
UNION ALL
SELECT
  "oranges" AS fruit,
  5 AS count,
   CURRENT_TIMESTAMP() as ingest_time
UNION ALL
SELECT
  "pears" AS fruit,
  1 AS count,
   CURRENT_TIMESTAMP() as ingest_time
UNION ALL
SELECT
  "bananas" AS fruit,
  0 AS count,
   CURRENT_TIMESTAMP() as ingest_time